<?php
/**
 * @package Gallina °)>
 * @subpackage core (g_)
 * @author David Dauvergne
 * @licence GNU Lesser General Public Licence see LICENCE file or http://www.gnu.org/licenses/lgpl.html
 */

/**
 * Gestion des erreurs de route
 *
 * @package Gallina °)>
 * @subpackage core (g_)
 */
class g_noroute extends g_module {

	private function _error404(){
		$rep = $this->MgetResponse('simplehtml');
		$rep->title('404 Not Found');
		$rep->content = "<h1>404 Not Found</h1>\n"
			."<p>Sorry, the requested page doesn't exist</p>"
			.'<p style="font-size:0.8em;font-style:italic">Page generated by °)&gt;</p>';
		$rep->statutCode(404);
		return $rep;
	}

	protected function errorHTTP(){
		$rep = $this->MgetResponse('simplehtml');
		$rep->title($this->MgetVarC('error_title'));
		$rep->content = $this->MgetVarC('error_content');
		$rep->statutCode($this->MgetVarC('error_code'));
		return $rep;
	}

	protected function noRoute(){
		if(GALLINA_DEBUG && $_SERVER['REQUEST_METHOD']!='GET' ){
			$rep = $this->MgetResponse('json');
			$rep->content = ajax::error(array('content' => 'Error type : route'),'Err-g-41');
		} else {
			$rep = $this->_error404();
		}
		return $rep;
	}

	protected function noAction(){
		if(GALLINA_DEBUG && $_SERVER['REQUEST_METHOD']!='GET' ){
			$rep = $this->MgetResponse('json');
			$rep->content = ajax::error(array('content' => 'Error type : action'),'Err-g-42');
		} else {
			$rep = $this->_error404();
		}
		return $rep;
	}

	protected function noModule(){
		if(GALLINA_DEBUG && $_SERVER['REQUEST_METHOD']!='GET' ){
			$rep = $this->MgetResponse('json');
			$rep->content = ajax::error(array('content' => 'Error type : module'),'Err-g-43');
		} else {
			$rep = $this->_error404();
		}
		return $rep;
	}

	protected function errorModuleNoRoute(){
		if(GALLINA_DEBUG && $_SERVER['REQUEST_METHOD']!='GET' ){
			$rep = $this->MgetResponse('json');
			$rep->content = ajax::error(array('content' => 'Error type : module/route,'),'Err-g-44');
		} else {
			$rep = $this->_error404();
		}
		return $rep;
	}

	protected function errorModuleNoRouteAction(){
		if(GALLINA_DEBUG && $_SERVER['REQUEST_METHOD']!='GET' ){
			$rep = $this->MgetResponse('json');
			$rep->content = ajax::error(array('content' => 'Error type : module/route/action,'),'Err-g-45');
		} else {
			$rep = $this->_error404();
		}
		return $rep;
	}
}
?>